version: '3.3'

volumes:
  pg_foodgram_data:
  foodgram_static:
  foodgram_media:


services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_foodgram_data:/var/lib/postgresql/data
  backend:
    image: sanzhar16/foodgram_backend
    env_file: ../.env
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/app/media
  frontend:
    image: sanzhar16/foodgram_frontend
    volumes:
      - foodgram_static:/app/result_build
  nginx:
    image: sanzhar16/foodgram_nginx
    env_file: ../.env
    ports:
      - "8050:80"
    volumes:
      - foodgram_static:/usr/share/nginx/html/
      - foodgram_media:/media
