# Generated by Django 3.2.3 on 2024-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
