# Generated by Django 3.2.3 on 2024-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=256, verbose_name='Единица измерения'),
        ),
    ]
